# Generated by Django 4.2.7 on 2023-12-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('imagem', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=100)),
            ],
        ),
    ]
