# Generated by Django 4.2.7 on 2023-12-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='imagens/')),
            ],
        ),
        migrations.DeleteModel(
            name='Fila',
        ),
    ]
