# Generated by Django 4.2.7 on 2023-12-04 01:05

from django.db import migrations, models
import fila.models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0002_imagem_delete_fila'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(upload_to=fila.models.subir_imagem),
        ),
    ]
