# Generated by Django 4.2.7 on 2023-12-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0003_alter_imagem_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='comentario',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagem',
            name='estado',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='imagem',
            name='titulo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
