# Generated by Django 4.2.7 on 2023-12-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0004_imagem_comentario_imagem_estado_imagem_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='estado',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
