# Generated by Django 4.2.7 on 2023-12-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0007_alter_imagem_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='curtida',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
